# see https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/build-spec-ref.html
version: 0.2

env:
  variables:
    IMAGE_NAME: data-mapping
    # ECRのURLは環境変数で指定する.
    REPOSITORY_URI: <REPOSITORY_URI>
    IMAGE_TAG: latest

phases:
  install:
    runtime-versions:
      # nodejs: 20
      nodejs: latest
    commands:
      # Docker buildするために必要なコマンドを実行する
      # runtime-versionで必要なruntimeを指定すれば基本不要
      # https://docs.aws.amazon.com/ja_jp/codebuild/latest/userguide/runtime-versions.html
      #- yum install -y nodejs npm

  pre_build:
    commands:
      # Test Codeがあれば実行する
      # test data-mapping-tool
      
  build:
    commands:
      # build app
      - docker build -t ${IMAGE_NAME} -f ./Dockerfile .

      
  post_build:
    commands:
      # push data-mapping-tool image tod ECR
      - aws ecr get-login-password --region ap-northeast-1 | docker login --username AWS --password-stdin ${REPOSITORY_URI}
      - docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${REPOSITORY_URI}/${IMAGE_NAME}:${IMAGE_TAG}
      - docker push ${REPOSITORY_URI}/${IMAGE_NAME}:${IMAGE_TAG}

      - echo "[{\"name\":\"${IMAGE_NAME}\",\"imageUri\":\"${REPOSITORY_URI}/${IMAGE_NAME}:${IMAGE_TAG}\"}]" > imagedefinitions.json
      - printf '{"Version":"1.0","ImageURI":"%s"}' ${REPOSITORY_URI}/${IMAGE_NAME}:${IMAGE_TAG} > imageDetail.json
      
      
artifacts:
    files:
      - imagedefinitions.json
      - imageDetail.json